---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

# - name: configure webserver
#   hosts: webservers
#   remote_user: root

#   roles:
#     - web

# - name: configure dbserver
#   hosts: dbservers
#   remote_user: root

#   roles:
#     - db